# Generated by Django 5.1.4 on 2024-12-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
                ("area", models.FloatField()),
                ("rooms", models.IntegerField()),
                ("floor", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("publication_date", models.DateField()),
                ("images", models.TextField()),
                ("realtor_id", models.IntegerField()),
            ],
        ),
    ]
