# Generated by Django 5.1.4 on 2024-12-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estator", "0003_realtor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="property_id",
            new_name="property",
        ),
    ]
