# Generated by Django 5.1.4 on 2024-12-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estator", "0004_rename_property_id_application_property"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="aplicant",
            new_name="applicant",
        ),
    ]
