# Generated by Django 5.1.4 on 2024-12-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estator", "0005_rename_aplicant_application_applicant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Realtor",
        ),
    ]
